spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.90.6.183:3306/sns
    username: sns
    password: sns!
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        format_sql: true
      use_sql_comments: true
    show-sql: true
logging:
  level: info